#ifndef CUSTOMADS_ALGORITHMS_SIEVE_OF_ERATOSTHENES_SIEVE_OF_ERATOSTHENES_HPP_
#define CUSTOMADS_ALGORITHMS_SIEVE_OF_ERATOSTHENES_SIEVE_OF_ERATOSTHENES_HPP_

#include <vector>

std::vector<bool> getPrimeNumbers(const int& n);

#endif  // CUSTOMADS_ALGORITHMS_SIEVE_OF_ERATOSTHENES_SIEVE_OF_ERATOSTHENES_HPP_