#ifndef CUSTOMADS_ALGORITHMS_SIEVE_OF_ERATOSTHENES_SIEVE_OF_ERATOSTHENES_HPP_
#define CUSTOMADS_ALGORITHMS_SIEVE_OF_ERATOSTHENES_SIEVE_OF_ERATOSTHENES_HPP_

#include <vector>

namespace ads {

std::vector<bool> getPrimeNumbers(const int& n);

}  // namespace ads

#endif  // CUSTOMADS_ALGORITHMS_SIEVE_OF_ERATOSTHENES_SIEVE_OF_ERATOSTHENES_HPP_