#ifndef CUSTOMADS_DATA_STRUCTURES_MIN_MAX_QUEUE_MIN_MAX_NODE_HPP_
#define CUSTOMADS_DATA_STRUCTURES_MIN_MAX_QUEUE_MIN_MAX_NODE_HPP_

struct MinMaxNode {
  int self_value;
  int min_value;
  int max_value;
};

#endif  // CUSTOMADS_DATA_STRUCTURES_MIN_MAX_QUEUE_MIN_MAX_NODE_HPP_
